---
- name: Update system
  yum: name='*' state=latest

- name: Restart server
  shell: sleep 2 && /sbin/shutdown -r now "Ansible system package upgraded"
  async: 1
  poll: 0
  ignore_errors: true

- name: waiting 30 secs for server to come back
  wait_for:
    host: "{{ inventory_hostname }}"
    port: 22
    state: started
    delay: 30
    timeout: 60
  vars:
    ansible_connection: local
